# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170612_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excrept',
            new_name='excerpt',
        ),
    ]
